### GET
GET http://localhost:8080/micro-company

### GET with invalid ID
GET http://localhost:8080/micro-company/1

### POST new microcompany
POST http://localhost:8080/micro-company
Content-Type: application/json

{
  "nome": "Newton paiva MEI",
  "cnpj": "03.364.378/0001-62",
  "email": "email@email.com"
}

### GET with ID
GET http://localhost:8080/micro-company/61aea915ff971357e65ae2ff

### PUT update Microcompany
PUT http://localhost:8080/micro-company/61aea915ff971357e65ae2ff
Content-Type: application/json

{
  "nome": "Newton paiva - ATUALIZADO -  MEI",
  "cnpj": "03.362.378/0001-62",
  "email": "emailatualizado@email.com"
}

### DELETE
DELETE http://localhost:8080/users/61aea915ff971357e65ae2ff